name: run_r_script_kumu_test

# Controls when the workflow will run
on:
  schedule:
    - cron: '44 10 * * *'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    env:
      MY_GOOGLE_PASSWORD: ${{ secrets.MY_GOOGLE_PASSWORD }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # set up R 
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
      
      # set up Pandoc
      - uses: r-lib/actions/setup-pandoc@master
      
      - name: step-1-install-packages & Query dependencies
        run: |
          install.packages('tidyverse')
          install.packages('googlesheets4')
          install.packages('remotes')
        #  saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        #  writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}
          
      - name: step-2-run-script
        run: 
          Rscript -e "source('scripts/convert_to_kumu.R')"
          
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m 'update Kumu vis' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
