# This is a basic workflow to help you get started with Actions

name: run_r_script_kumu_test

# Controls when the workflow will run
on:
  schedule:
    - cron: '55 12 * * *'

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # set up R 
      - uses: r-lib/actions/setup-r@v1
      # set up Pandoc
      - uses: r-lib/actions/setup-pandoc@v1
      - name: step-1-install-packages
        run: 
          Rscript -e "install.packages(c('tidyverse', 'googlesheets4'))"
      - name: step-2-run-script
        run: 
          Rscript -e "source('scripts/convert_to_kumu')"
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add extra/packages-used.png
          git commit -m 'update Kumu vis' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
          
